version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: speedtest-tracker_speedtest-tracker_1
      APP_PORT: 80

  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - OOKLA_EULA_GDPR=true
    volumes:
      - ./data:/config
    ports:
      - 8765:80
    restart: unless-stopped