version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: speedtest-tracker_speedtest-tracker_1
      APP_PORT: 8765

  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_CONNECTION=sqlite
      - APP_KEY= #optional
      - DB_HOST= #optional
      - DB_PORT= #optional
      - DB_DATABASE= #optional
      - DB_USERNAME= #optional
      - DB_PASSWORD= #optional
    volumes:
      - ./data:/config
    restart: unless-stopped
